### ISSUE TITLE
nextcloud ldap vcard import error

### ISSUE THREAD

**Issue by tursadilar** [nextcloud/ldap_contacts_backend#19] opened 2021-04-14 06:17 UTC
good morning i have successfully established a connection with ldap.
fresh nextcloud 21 instance
parameter:
`sudo -u www-data php occ ldap_contacts:add test \
  --host=localhost \
  --port=389 \
  --trans_enc=tls \
  --bindDN='cn=admin,dc=...' \
  --bindPwd=****** \
  --filter='(objectClass=inetOrgPerson)' \
  --base='ou=users,dc=...' \
  --attrs=cn \
  --attrs=mail \
  --attrs=telephoneNumber \
  --mapping=EMAIL:mail \
  --mapping=FN:cn \
  --mapping=TEL:telephoneNumber`

now I get the following error in nextcloud by searching contacts:

`
Error: Undefined index: PHOTO at /var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/ContactsAddressBook.php#97
/var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/ContactsAddressBook.php - line 97:
OC\Log\ErrorHandler::onError()
/var/www/nextcloud/lib/private/ContactsManager.php - line 52:
OCA\LDAPContactsBackend\Service\ContactsAddressBook->search()
/var/www/nextcloud/lib/private/Contacts/ContactsMenu/ContactsStore.php - line 87:
OC\ContactsManager->search()
/var/www/nextcloud/lib/private/Contacts/ContactsMenu/Manager.php - line 71:
OC\Contacts\ContactsMenu\ContactsStore->getContacts()
/var/www/nextcloud/core/Controller/ContactsMenuController.php - line 61:
OC\Contacts\ContactsMenu\Manager->getEntries()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:
OC\Core\Controller\ContactsMenuController->index()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 993:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 37:
OC::handleRequest()
`

error in nextcloud when trying to add the contact
`
Error: Illegal string offset 'value' at /var/www/nextcloud/apps/dav/lib/CardDAV/AddressBookImpl.php#157
/var/www/nextcloud/apps/dav/lib/CardDAV/AddressBookImpl.php - line 157:
OC\Log\ErrorHandler::onError()
/var/www/nextcloud/apps/ldap_contacts_backend/lib/Controller/ContactsController.php - line 156:
OCA\DAV\CardDAV\AddressBookImpl->createOrUpdate()
/var/www/nextcloud/apps/ldap_contacts_backend/lib/Controller/ContactsController.php - line 105:
OCA\LDAPContactsBackend\Controller\ContactsController->createCard()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:
OCA\LDAPContactsBackend\Controller\ContactsController->import()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 993:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 37:
OC::handleRequest()
`

**Comment by blizzz** [comment] 2021-04-23 21:03
I have not spotted the first error yet, but  the second. And that's a regression caused by https://github.com/nextcloud/server/pull/23317

**Comment by blizzz** [comment] 2021-04-30 19:44
Fix in https://github.com/nextcloud/server/pull/26845 for the import.

The undefined index is fixed in https://github.com/nextcloud/ldap_contacts_backend/pull/25

**Comment by blizzz** [comment] 2021-05-03 17:36
This is fixed in Nextcloud server and to be shipped with 21.0.2.

**Closed by blizzz** 2021-05-03 17:36 UTC
